import type { PDFBuilder } from '../generator'
import type { InstrumentId } from '@/lib/instruments'

const ABOUT: Record<InstrumentId,string> = {
  phq9: 'PHQ-9 (Patient Health Questionnaire-9): Developed by Drs. Robert L. Spitzer, Janet B.W. Williams, Kurt Kroenke and colleagues, with an educational grant from Pfizer Inc. No permission required to reproduce, translate, display or distribute. Scores: 0–4 minimal, 5–9 mild, 10–14 moderate, 15–19 moderately severe, 20–27 severe.',
  gad7: 'GAD-7 (Generalized Anxiety Disorder-7): Developed by Spitzer et al. (2006) as a brief anxiety screener; widely used in primary care and research. Typical score bands: 0–4 minimal, 5–9 mild, 10–14 moderate, 15–21 severe.',
  phq2: 'PHQ-2: First two items of PHQ-9 used as an ultra-brief depression screener. Positive screens should be followed by fuller clinical assessment (often PHQ-9).',
  gad2: 'GAD-2: First two items of GAD-7 used as an ultra-brief anxiety screener. Positive screens should be followed by fuller clinical assessment (often GAD-7).',
  who5: 'WHO-5 Well-Being Index: Developed by the WHO Collaborating Centre for Mental Health, Frederiksborg General Hospital, Hillerød; widely used as a wellbeing measure and free for non-commercial use.',
  sleep: 'Sleep quick check: Non-validated personal context tracker, intended to complement formal screening tools.',
  stress: 'Stress quick check: Non-validated personal context tracker, intended to complement formal screening tools.',
}

export function addAppendixSection(builder: PDFBuilder, used: InstrumentId[], sourceUrl?: string) {
  builder.addPageBreakIfNeeded(80)
  builder.addHeading('Appendix & attribution', 2)
  builder.addHeading('About the instruments', 3)
  used.forEach((id)=> builder.addParagraph(ABOUT[id], { muted: true }))
  builder.addSpacer(2)
  builder.addHeading('About this report', 3)
  builder.addParagraph("This report was generated by MindMeter, a privacy-focused self-report tool. All check-in data is stored locally on the user's device using browser storage (IndexedDB). No data is transmitted to any server. This report was generated on the user's device and shared at their discretion.", { muted: true })
  builder.addSpacer(2)
  builder.addHeading('Important limitations', 3)
  ;[
    'These are screening instruments, not diagnostic tools. Diagnosis requires clinical evaluation.',
    'Scores reflect self-reported symptoms over the recall window (typically 2 weeks). Recall accuracy varies.',
    'Trends from short ranges or sparse check-ins should be interpreted cautiously.',
    'This report does not include qualitative context that a clinical interview would provide.',
  ].forEach((line)=>builder.addParagraph(`• ${line}`, { muted: true }))

  if (sourceUrl) {
    builder.cursor.y = 289
    builder.addParagraph(`MindMeter is open-source software. Source: ${sourceUrl}`, { muted: true })
  }
}
