import type { PDFBuilder } from '../generator'
import { PDF_PAGE, PDF_THEME } from '../theme'

type Checkin = { type: string; timestamp: Date | string; score: number | null; severityBand: string | null }
type Response = { checkinId: number; questionId: string; value: number | null }

type CoverOpts = {
  preparedBy?: string
  therapist?: string
  appointmentDate?: string
  startDate: Date
  endDate: Date
  generatedAt: Date
  includedInstruments: string[]
  checkins: (Checkin & { id?: number })[]
  responses?: Response[]
  autoTable?: (args: { head: string[][]; body: string[][]; startY: number }) => void
}

function fmtDate(d: Date) { return d.toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' }) }
function fmtDateShort(d: Date) { return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) }

function trend(scores: number[]) {
  if (scores.length < 6) return '—'
  const third = Math.max(1, Math.floor(scores.length / 3))
  const early = scores.slice(0, third)
  const late = scores.slice(-third)
  const a = early.reduce((x, y) => x + y, 0) / early.length
  const b = late.reduce((x, y) => x + y, 0) / late.length
  const d = b - a
  if (d <= -1) return '↓ Improving'
  if (d >= 1) return '↑ Worsening'
  return '→ Stable'
}

export function addCoverPage(builder: PDFBuilder, opts: CoverOpts) {
  builder.addHeading('Self-Report Mood Check-in Summary', 1)
  if (opts.preparedBy) builder.addParagraph(`Prepared by: ${opts.preparedBy}`)
  const days = Math.max(1, Math.round((opts.endDate.getTime() - opts.startDate.getTime()) / 86400000) + 1)
  builder.addParagraph(`Date range covered: ${fmtDateShort(opts.startDate)} – ${fmtDateShort(opts.endDate)} (${days} days)`)
  builder.addParagraph(`Exported ${fmtDate(opts.generatedAt)} at ${opts.generatedAt.toLocaleTimeString()}`)
  if (opts.therapist) builder.addParagraph(`For: ${opts.therapist}`)
  if (opts.appointmentDate) builder.addParagraph(`Appointment: ${opts.appointmentDate}`)
  builder.addSpacer(3)

  const phq9 = opts.checkins.filter(c => c.type === 'phq9')
  const phqIds = new Set(phq9.map(c => c.id).filter(Boolean) as number[])
  const q9Hits = (opts.responses ?? []).filter(r => phqIds.has(r.checkinId) && r.questionId === 'phq9_q9' && (r.value ?? 0) >= 1)
  if (q9Hits.length > 0) {
    const mostRecent = phq9.sort((a,b)=>+new Date(b.timestamp)-+new Date(a.timestamp))[0]
    builder.addParagraph(`Note: Item 9 (thoughts of being better off dead or self-harm) was endorsed on ${q9Hits.length} of ${phq9.length} PHQ-9 check-ins. Most recent: ${fmtDateShort(new Date(mostRecent.timestamp))}.`, { muted: true })
    builder.addSpacer(2)
  }

  const rows = opts.includedInstruments.map((id) => {
    const list = opts.checkins.filter(c => c.type === id).sort((a,b)=>+new Date(a.timestamp)-+new Date(b.timestamp))
    const scores = list.map(c=>c.score).filter((s):s is number=>s!==null)
    const latest = list.at(-1)
    const avg = scores.length ? (scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1) : '—'
    return [id.toUpperCase(), String(list.length), latest?.score?.toString() ?? '—', latest?.severityBand ?? '—', avg, trend(scores)]
  })

  if (opts.autoTable) {
    opts.autoTable({
      head: [['Instrument', '# Check-ins', 'Latest score', 'Latest severity', 'Avg', 'Trend']],
      body: rows,
      startY: builder.cursor.y + 2,
    })
    builder.cursor.y += 42
  } else {
    builder.addParagraph('Summary table unavailable in this runtime (autoTable not installed).', { muted: true })
  }

  builder.addSpacer(2)
  builder.addHeading('How to read this report', 3)
  builder.addParagraph('This report contains self-administered screening questionnaires, completed by the user on their own device. Scores indicate symptom levels, not diagnoses. Trends are calculated from the most recent third versus the earliest third of the date range. PHQ-9 and GAD-7 are validated screening instruments (Pfizer, free for clinical use); WHO-5 is a wellbeing index (WHO Collaborating Centre).', { muted: true })

  builder.cursor.y = PDF_PAGE.PAGE_HEIGHT - 18
  builder.addParagraph("Generated by MindMeter, an open-source self-report tool. Data stored locally on the user's device.", { muted: true })
}
